treat restarted task as done
golemfactory/golem-electron pull request #192
Opened 2018-01-08 15:13 UTC by etam

Fixes golemfactory/golem#1748
Supplements golemfactory/golem#1866

2018-01-08 15:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem-electron?pullRequest=192) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem-electron?pullRequest=192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem-electron?pullRequest=192) it.</sub>

2018-01-16 13:19 UTC, mdtanrikulu commented
Waiting for golemfactory/golem#1866 merge.

2018-01-16 13:29 UTC, mdtanrikulu requested changes

2018-01-16 13:29 UTC, mdtanrikulu commented on src/components/tasks/Table.js
> -                    (_item.status == status.RESTART && _item.progress > 0))
If we're holding progress after restart, we need to keep this condition to avoid from opening preview screen without progress.

2018-01-16 21:33 UTC, mdtanrikulu approved these changes

2018-01-17 07:52 UTC, etam commented
@mdtanrikulu please merge this
Github says to me "You're not authorized to merge this pull request."

2018-01-17 14:49 UTC, merged