Specify core rpc port
golemfactory/golem-electron pull request #67
Opened 2017-07-20 15:30 UTC by jiivan

When _golem core_ has non standard port in settings it won't connect with frontend. That's why it needs to be specified in spawn invocation.

2017-07-20 16:36 UTC, mfranciszkiewicz requested changes

2017-07-20 16:36 UTC, mfranciszkiewicz commented on electron/golem_handler.js
> +        this.processArgs = processArgs || ['--nogui', '-r', '0.0.0.0:61000'];
Please use 127.0.0.1 instead of 0.0.0.0

2017-07-20 16:58 UTC, jiivan commented on electron/golem_handler.js
> +        this.processArgs = processArgs || ['--nogui', '-r', '0.0.0.0:61000'];
good point :)

2017-07-21 09:01 UTC, mfranciszkiewicz approved these changes

2017-07-21 10:10 UTC, merged