Developer mode
golemfactory/golem-electron pull request #93
Opened 2017-09-08 14:46 UTC by mdtanrikulu

2017-09-23 08:13 UTC, maaktweluit requested changes
sorry for not focusing much on the app / logic / flows, i'm new to this application so can not see the bigger picture yet.

Most comments are small and good practice proposals I have learned from the past.

2017-09-23 08:13 UTC, maaktweluit commented on electron/config_storage.js
> +var electron = require('electron');
any reason not to use `const` here?

2017-09-23 08:13 UTC, maaktweluit commented on electron/config_storage.js
> +let setConfig = function(key, value) {
could keep it simple with just
`function setConfig(...`
same for getter

2017-09-23 08:13 UTC, maaktweluit commented on electron/config_storage.js
> +module.exports = global.configStorage = configStorage
no newline at end of file is bad for git diffs

2017-09-23 08:13 UTC, maaktweluit commented on electron/debug_handler.js
> +module.exports = global.log = logger
white line at eof

2017-09-23 08:13 UTC, maaktweluit commented on electron/golem_handler.js
> +const log = require('./debug_handler.js')
we can `require().getLogger('FILE_IDENTIFIER')` to not repeat the `'MAIN_PROCESS > GOLEM_HANDLER'` later

`getLogger` is pseudo code, not sure if it exists ( yet ;) )

2017-09-23 08:13 UTC, maaktweluit commented on index.js
> +//const createTray = require('./electron/tray_handler.js')
commented out to stay? we used to only allow commented out code if it has an explanation comment.

2017-09-23 08:13 UTC, maaktweluit commented on src/components/tasks/TaskDetail.js
> +        // console.log("price", price);
logs to stay? could become `log.debug` or `log.silly`

2017-09-23 08:13 UTC, maaktweluit commented on src/reducers/frame/single.js
> +const {SET_FRAMES_WITH_SUBTASKS, SET_SUBTASKS_BORDER, SET_PREVIEW_LIST, SET_SUBTASKS_LIST, SET_SUBTASKS_VISIBILITY, SET_FRAME_ID, NEXT_FRAME, PREVIOUS_FRAME, CLEAR_TASK_PLAIN} = dict
maybe break down long line?

2017-09-23 08:13 UTC, maaktweluit commented on src/sagas/frame/index.js
> +    console.log("payload", payload);
`log.verbose` or more debuggy?

2017-09-23 08:13 UTC, maaktweluit commented on src/sagas/stats.js
> +}
eof

2017-09-25 10:55 UTC, mdtanrikulu commented on src/sagas/frame/index.js
> +    console.log("payload", payload);
debug

2017-09-25 10:55 UTC, mdtanrikulu commented on electron/golem_handler.js
> +const log = require('./debug_handler.js')
nice idea! I'll implement it soon.

2017-10-13 15:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/golemfactory/golem-electron?pullRequest=93) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/golemfactory/golem-electron?pullRequest=93) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mdtanrikulu<br/>:x: badb<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/golemfactory/golem-electron?pullRequest=93) it.</sub>

2017-10-13 15:24 UTC, badb commented
@mdtanrikulu Can we merge this, pleaaaase?

2017-10-13 15:32 UTC, mdtanrikulu commented
Sure, let me check after merging dev into developer mode, then I'll merge it.

2017-10-18 15:54 UTC, merged